bridge:
  # 网桥地址
  addr: :7000
  # 网桥代理地址
  proxyAddr: :8888
service:
  # 分组
  group: tangtangtang
  # 网桥地址，接受多个网桥地址使用`,`分割，如 :7000,:7001
  bridgeAddr: :7000
  # 密码
  password: 123456
proxy:
  # 本地代理地址
  addr: :8080
  # 网桥代理地址
  bridgeProxyAddr: :8888
  # 分组
  group: tangtangtang
  # 密码
  password: 123456
  # 代理类型 http || socks5
  type: socks5
mapping:
  # 本地代理地址
  addr: :8080
  # 网桥代理地址
  bridgeProxyAddr: :8888
  # 映射地址
  realAddr: ''
  # 分组
  group: tangtangtang
  # 密码
  password: 123456